repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.14.2
  hooks:
    - id: commitizen
      stages: [commit-msg]

# Stop commits to master
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0  # Use the ref you want to point at
  hooks:
  - id: no-commit-to-branch
    stages: [commit, push]
    args: [--branch, master]  
  - id: check-merge-conflict
    stages: [commit, push]

- repo: https://github.com/outcome-co/action-check-todos
  rev: v1.7.5
  hooks:
  - id: check-todos
    args: ['--ignore','coverage','**/*']
    stages: [push]

- repo: local
  hooks:

  - id: autoupdate
    name: autoupdate
    language: system
    stages: [push]
    verbose: true
    entry: poetry run pre-commit autoupdate
    pass_filenames: false

  - id: checks
    name: checks
    language: system  # Running on the local system
    stages: [push]
    verbose: true
    entry: poetry run inv check.all
    types: [file, python]  # Only triggered if python files are changed in the commit
    pass_filenames: false

  - id: test
    name: test
    language: system  # Running on the local system
    stages: [push]
    verbose: true
    entry: poetry run inv test.unit
    types: [file, python]  # Only triggered if python files are changed in the commit
    pass_filenames: false
